#source $HOME/.zsh/.zsh.path

# Sometimes I like to keep a history...
export SAVEHIST=2000
export HISTFILE=$HOME/.zsh/zsh.history
export LESSHISTFILE="/dev/null" # no 'less' history

export CVS_RSH=ssh

# Most people are ok with vim
export EDITOR=vim
export VISUAL=vim

# Set up the parameters for 'less' ... and use it
export LESS='-emiSRX'
export PAGER=less

umask 077

export PS1="\t \u@\h \n\w\\$ "
export TERM=$TERM
# Don't have the shell check for mail
unset MAIL         

ulimit -c 0
